### PR TITLE
Wip/lece fixes

### LINKED ISSUE #116: multiple entry for birthplace & deathplace
There can be multiple entries for theses properties in various languages.
Alll the entries should be listed

### PR DESCRIPTION
**Pull request by SepidehAlassi**
Fixes w.r.t recent feedback

closes #116 & #117

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I will do this review today.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer thank you, but last night I found an issue in person template(see #117), which I am planning to resolve in this pull request. If you don't mind, can you please do this pull request tomorrow?

**Comment by tobiasschweizer** [comment]
Of course, no problem!

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I am thinking about hiding the property "mentionedIn" from persons and bibliographical items and instead show the incoming links for these resources. mentionedIn was supposed to be used for editors, it is not important for the normal users, however having access to where the resources are referenced through a list of "incoming links" is more useful for historians. what do you think?

**Comment by tobiasschweizer** [comment]
> I am thinking about hiding the property "mentionedIn" from persons and bibliographical items and instead show the incoming links for these resources. mentionedIn was supposed to be used for editors, it is not important for the normal users, however having access to where the resources are referenced through a list of "incoming links" is more useful for historians. what do you think?

That's a good point. I think editors should rather use the generic template (`/resource`) whereas researchers should use the type specific templates. However, users could find information using the search that is not displayed in the type specific templates. I am not sure how we are going to deal with that.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer then I will deactivate the mentionedIn. For now, I would say we display the incoming links, with under "Referenced In" to be a bit more user-friendly. What do u think?

**Comment by tobiasschweizer** [comment]
> then I will deactivate the mentionedIn

You mean you do not display it it the template? That's ok.

> For now, I would say we display the incoming links, with under "Referenced In" to be a bit more user-friendly. What do u think?

Ok!

**Comment by SepidehAlassi** [comment]
> You mean you do not display it it the template? That's ok.

yeah, I just comment it out

**Comment by SepidehAlassi** [comment]
@tobiasschweizer this pull request can be reviewed now.

**Comment by tobiasschweizer** [comment]
ok, I try to do it in the afternoon

**Comment by tobiasschweizer** [comment]
Do I need updated data?

**Comment by SepidehAlassi** [comment]
> Do I need updated data?

no, you don't.

**Comment by tobiasschweizer** [comment]
Ok, I will do the review now then

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Do I need https://github.com/dhlab-basel/Knora/pull/1222 in Knora? I think you mentioned it earlier.

File: src/app/resource/biblio-items/biblio-items.component.ts [hunk 1]
```diff
@@ -148,5 +148,7 @@ export class BiblioItemsComponent extends BeolResource {
```
Comment (tobiasschweizer) [inline src/app/resource/biblio-items/biblio-items.component.ts]: Can the properties that are commented out be removed "/* // Unused properties (names come from Knora biblio ontology)"?

File: src/app/resource/biblio-items/biblio-items.component.ts [hunk 2]
```diff
@@ -148,5 +148,7 @@ export class BiblioItemsComponent extends BeolResource {
 
         this.props = props;
     }
-
```
Comment (tobiasschweizer) [inline src/app/resource/biblio-items/biblio-items.component.ts]: Please add a newline

File: src/app/resource/letter/letter.component.ts [hunk 3]
```diff
@@ -101,5 +101,8 @@ export class LetterComponent extends BeolResource {
         this.props = props;
 
     }
+    showIncomingRes(resIri, resType) {
```
Comment (tobiasschweizer) [inline src/app/resource/letter/letter.component.ts:105]: Please add a newline.

File: src/app/resource/person/person.component.html [hunk 4]
```diff
@@ -29,47 +28,83 @@ <h2 *ngIf="resource.label" class="mat-display-1 margins">{{resource?.label}}</h2
...
             <section class="links">
 
                 <div *ngIf="props?.IAF[0]">
                     <h4 class="subheading-2">{{ontologyInfo?.getLabelForProperty(props?.IAF[0].propIri)}}</h4>
                     <p class="mat-list-item-content" [kuiGnd]="props?.IAF[0].getContent()"></p>
                 </div>
+            </section>
+            <div *ngIf="props?.givenName[0]">
+                <h4 class="subheading-2">{{ontologyInfo?.getLabelForProperty(props?.givenName[0].propIri)}}: </h4>
+                <p *ngFor="let m of props?.givenName">
```
Comment (tobiasschweizer) [inline src/app/resource/person/person.component.html]: Could you use a better name instead of `m`?

File: src/app/resource/publisher/publisher.component.html [hunk 5]
```diff
@@ -47,18 +47,26 @@ <h4 class="subheading-2">{{ontologyInfo?.getLabelForProperty(props?.publishingPe
                         </mat-list-item>
                     </mat-list>
                 </div>
-                <div *ngIf="props?.mentioned[0]">
+               <!-- <div *ngIf="props?.mentioned[0]">
```
Comment (tobiasschweizer) [inline src/app/resource/publisher/publisher.component.html:50]: Do we still need this code?

File: src/app/landing-page/landing-page.component.html [hunk 6]
```diff
@@ -104,7 +105,7 @@ <h2 mat-card-title>Leonhardi Euleri Commercium Epistolicum</h2>
         <mat-divider></mat-divider>
 
         <section>
-            <h3 mat-card-subtitle>BEBB</h3>
+            <!--<h3 mat-card-subtitle>BEBB</h3>-->
```
Comment (tobiasschweizer) [inline src/app/landing-page/landing-page.component.html:108]: Do we still need that?

File: src/app/resource/biblio-items/biblio-items.component.html [hunk 7]
```diff
@@ -179,18 +179,31 @@ <h4 class="subheading-2">{{ontologyInfo?.getLabelForProperty(props?.comment[0].p
                 </read-text-value>
             </div>
 
-            <div *ngIf="props?.mentionedIn[0]">
+           <!-- <div *ngIf="props?.mentionedIn[0]">
```
Comment (tobiasschweizer) [inline src/app/resource/biblio-items/biblio-items.component.html:182]: Do we still need that?

**Review by tobiasschweizer — COMMENTED** [review]
I used `develop` in Knora.

File: src/app/resource/publisher/publisher.component.html (hunk 5 above)
Comment (SepidehAlassi) [reply src/app/resource/publisher/publisher.component.html:50]: maybe, lets see the reaction when BEZ people realize this property is gone 😄

File: src/app/landing-page/landing-page.component.html (hunk 6 above)
Comment (SepidehAlassi) [reply src/app/landing-page/landing-page.component.html:108]: Same answer as above! I am afraid we will be bombarded with criticism after deployment.
I left it to be there just in case they want it back. It seems like they can not make their mind!

File: src/app/resource/biblio-items/biblio-items.component.html (hunk 7 above)
Comment (SepidehAlassi) [reply src/app/resource/biblio-items/biblio-items.component.html:182]: Same answer as above!

File: src/app/resource/person/person.component.html (hunk 4 above)
Comment (SepidehAlassi) [reply src/app/resource/person/person.component.html]: yes.

File: src/app/resource/biblio-items/biblio-items.component.ts (hunk 1 above)
Comment (SepidehAlassi) [reply src/app/resource/biblio-items/biblio-items.component.ts]: Flavie has added them for the future. Right now we don't have these data, but as soon as Werkeverzeichnis bibliography is there, we will need them and have to adapt the templates.

**Comment by tobiasschweizer** [comment]
@SepidehAlassi Shall I have another look at this PR?

**Comment by SepidehAlassi** [comment]
@tobiasschweizer 

> Shall I have another look at this PR?

yeah, would be good if you have a quick look and approve it. 😆

File: src/app/resource/letter/letter.component.ts (hunk 3 above)
Comment (SepidehAlassi) [reply src/app/resource/letter/letter.component.ts:105]: done!

**Review by tobiasschweizer — APPROVED** [review]
